apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-akka-config
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
data:
  akka.conf: |
    akka {
        stdout-loglevel = INFO
        loggers=["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
        loglevel = INFO
        log-config-on-start = on
        actor {
            debug {
                    receive = on
                    autoreceive = on
                    lifecycle = on
                    event-stream = on
                    unhandled = on
            }
        }
    }
