apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    {{- include "app.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }

