apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodes.taint }}
                    operator: In
                    values:
                      - {{ .Values.nodes.taintValue }}
      tolerations:
        - key: {{ .Values.nodes.taint }}
          operator: Equal
          value: {{ .Values.nodes.taintValue }}
          effect: NoSchedule
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: APPLICATION_VERSION
              value: {{ .Values.image.tag }}
            - name: PROTEUS__DATADOG_SITE
              value: {{ .Values.logs.datadogSite }}
            - name: PROTEUS__DD_STATSD_HOST
              value: {{ .Values.metrics.statsd_host }}
            - name: PROTEUS__DD_STATSD_PORT
              value: {{ .Values.metrics.statsd_port | quote }}
            - name: PROTEUS__DEFAULT_LOG_LEVEL
              value: {{ .Values.logs.logLevel | quote }}
  {{- toYaml .Values.apm.environment | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources:
            limits:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
            - name: {{ template "app.name" . }}-akka-config
              mountPath: /app/akka.conf
              subPath: akka.conf
            - name: {{ template "app.name" . }}-secrets
              mountPath: /app/kube-config/
              readOnly: true
      volumes:
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
        - name: {{ template "app.name" . }}-config
          configMap:
            name: {{ template "app.name" . }}-config
        - name: {{ template "app.name" . }}-akka-config
          configMap:
            name: {{ template "app.name" . }}-akka-config
