name: Release a new version

on: workflow_dispatch

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    # Remove the line below and uncomment the next one
    if: ${{ false }}
    #if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: SneaksAndData/github-actions/semver_release@v0.1.6
        with:
          major_v: 0
          minor_v: 0
